# Generated by Django 5.0.6 on 2026-05-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10)),
                ('action', models.CharField(max_length=80)),
                ('actor', models.CharField(blank=True, help_text="User email or 'system'", max_length=200)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero', 'Homepage hero'), ('about', 'About page banner'), ('highlight_dolphin', 'Highlight: dolphins'), ('highlight_manatee', 'Highlight: manatees'), ('highlight_rocket', 'Highlight: rocket'), ('gallery_1', 'Gallery 1'), ('gallery_2', 'Gallery 2'), ('gallery_3', 'Gallery 3'), ('gallery_4', 'Gallery 4'), ('gallery_5', 'Gallery 5'), ('gallery_6', 'Gallery 6'), ('gallery_7', 'Gallery 7'), ('gallery_8', 'Gallery 8'), ('og_default', 'Default social share image')], max_length=40, unique=True)),
                ('image', models.ImageField(upload_to='site/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Dolphin Island Tours', max_length=120)),
                ('tagline', models.CharField(default='Explore the wonders of the Space Coast.', max_length=240)),
                ('seo_title', models.CharField(default='Dolphin Island Tours – Space Coast Wildlife & Sunset Cruises', max_length=70)),
                ('seo_description', models.CharField(default='Small-group wildlife and sunset boat tours from Merritt Island, FL. Book your Space Coast adventure online.', max_length=180)),
                ('seo_keywords', models.CharField(default='dolphin tours, merritt island, space coast, sunset cruise, wildlife tour, florida boat tour', max_length=240)),
                ('contact_email', models.EmailField(default='lewis@dolphinislandtours.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(default='2700 Harbortown Drive, Merritt Island, FL', max_length=240)),
                ('hours', models.CharField(default='Open daily 9 AM – 5 PM', max_length=120)),
                ('google_analytics_id', models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX', max_length=40)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('tripadvisor_url', models.URLField(blank=True)),
                ('robots_txt', models.TextField(default='User-agent: *\nAllow: /\nSitemap: /sitemap.xml')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload from your computer. Recommended 1600×1200.', null=True, upload_to='tours/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social share preview. 1200×630.', null=True, upload_to='tours/og/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Google snippet. Best 140–160 chars.', max_length=180),
        ),
        migrations.AddField(
            model_name='tour',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated.', max_length=240),
        ),
        migrations.AddField(
            model_name='tour',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Browser tab + Google. Best ≤60 chars.', max_length=70),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_url',
            field=models.CharField(blank=True, help_text='Optional fallback URL if no upload.', max_length=500),
        ),
    ]
