# Generated by Django 5.0.6 on 2026-05-21 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tour_pricing_party_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name.', max_length=120)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Plain text or HTML. Variables: {name}, {promo_code}.')),
                ('audience', models.CharField(choices=[('all_users', 'All registered users'), ('subscribed_users', 'Subscribed mailing list only'), ('both', 'Users + mailing list'), ('manual', 'Manual emails only (paste below)')], default='all_users', max_length=20)),
                ('manual_emails', models.TextField(blank=True, help_text="One email per line. Used with 'manual' or added to other audiences.")),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=400)),
                ('attach_promo', models.BooleanField(default=False, help_text='Generate a unique promo code per recipient.')),
                ('promo_kind', models.CharField(choices=[('percent', 'Percent off'), ('amount', 'Amount off ($)')], default='percent', max_length=10)),
                ('promo_percent_off', models.PositiveSmallIntegerField(default=10)),
                ('promo_amount_off_cents', models.PositiveIntegerField(default=0)),
                ('promo_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated, e.g. vip,2024-guest', max_length=240)),
                ('subscribed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mailing list entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(blank=True, help_text="Internal name, e.g. 'Summer 10% blast'", max_length=120)),
                ('kind', models.CharField(choices=[('percent', 'Percent off'), ('amount', 'Amount off ($)')], default='percent', max_length=10)),
                ('percent_off', models.PositiveSmallIntegerField(default=10, help_text='Used when kind=percent. 1–100.')),
                ('amount_off_cents', models.PositiveIntegerField(default=0, help_text='Used when kind=amount. Cents.')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='0 = unlimited.')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('locked_to_email', models.EmailField(blank=True, help_text='Optional: only this email can redeem.', max_length=254)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to='api.emailcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.promocode'),
        ),
    ]
