# Generated by Django 5.0.6 on 2026-05-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepts_marketing',
            field=models.BooleanField(default=False, help_text='User opted in to deals, promo codes, and newsletter emails.'),
        ),
    ]
