# Generated by Django 5.0.6 on 2026-05-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_tour_tax_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="tax_rate_percent",
        ),
        migrations.AlterField(
            model_name="tour",
            name="tax_rate_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Sales tax percentage for this tour. Example: 7.00 for 7%.",
                max_digits=5,
            ),
        ),
    ]
