# Generated by Django 5.0.6 on 2026-06-14 16:07

from django.db import migrations, models

REMOVED_AUTH_PAGES = ["login", "signup", "account", "bookings", "forgot_password", "reset_password"]


def delete_customer_auth_pages(apps, schema_editor):
    PageContent = apps.get_model("api", "PageContent")
    PageContent.objects.filter(page__in=REMOVED_AUTH_PAGES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_pagecontent_page'),
    ]

    operations = [
        migrations.RunPython(delete_customer_auth_pages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('tours', 'Tours listing'), ('book', 'Booking'), ('reviews', 'Reviews'), ('about', 'About'), ('contact', 'Contact'), ('find_booking', 'Find booking')], max_length=32, unique=True),
        ),
    ]
