# Generated by Django 5.0.6 on 2026-06-14 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_customer_auth_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='percent_off',
            field=models.PositiveSmallIntegerField(default=10, help_text='Used when kind=percent. 1–100.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
