# Generated by Django 5.0.6 on 2026-06-14 16:29

from django.db import migrations, models


def backfill_name_split(apps, schema_editor):
    """Split existing customer_name into first/last for legacy bookings."""
    Booking = apps.get_model("api", "Booking")
    for booking in Booking.objects.all().only("id", "customer_name", "customer_first_name", "customer_last_name"):
        parts = (booking.customer_name or "").strip().split()
        if not parts:
            continue
        booking.customer_last_name = parts[-1][:60]
        booking.customer_first_name = (" ".join(parts[:-1]) or parts[-1])[:60]
        booking.save(update_fields=["customer_first_name", "customer_last_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_promocode_percent_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.RunPython(backfill_name_split, migrations.RunPython.noop),
    ]
